# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
        
    # Build morphir application
    - name: Build morphir application
    - uses: actions/setup-node@v1.4.1
    - uses: justgook/setup-elm@v1
    - run: |
        npm install -g morphir-elm
        morphir-dapr -d
        
    # Login to Azure Container Registry, build and push image
    - name: Login to azure container registry
      env:
        ACR_SERVER: daprapps.azurecr.io
        APP_NAME: books_and_records
      uses: azure/docker-login@v1
      with: 
        login-server: $ACR_SERVER
        username: ${{ secrets.SERVICE_PRINCIPAL_CLIENT_ID }}
        password: ${{ secrets.SERVICE_PRINCIPAL_SECRET }}
    - run: |
        docker build . --tag $ACR_SERVER/$APP_NAME:${{ github.sha }}
        docker push $ACR_SERVER/$APP_NAME:${{ github.sha }} 
        
    # Login to azure azzount
    - name: Azure login
      uses: azure/login@v1
      with: 
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    # Check azure login status #
    - run: |
        az webapp list --query "[?state='Running']" 
 
